[package]
name = "llogin"
version = "1.3.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.20"
ureq = { version = "^2.6", features = ["native-tls"] }
